# Generated by Django 5.2.6 on 2025-09-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField()),
                ('car_model', models.CharField()),
                ('year', models.DateField()),
                ('color', models.CharField()),
                ('engine_type', models.CharField()),
                ('fuel_type', models.CharField()),
                ('transmission', models.CharField()),
                ('seating_capacity', models.IntegerField()),
                ('price', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
    ]
